#!/bin/bash
# setup_oiio_container.sh - Create a distrobox container with oiiotool + OCIO
#
# Creates an Ubuntu 24.04 container ("oiio-box") with openimageio-tools and
# OpenColorIO, then installs a wrapper at ~/bin/oiiotool so host scripts can
# call oiiotool transparently.
#
# Can be run standalone or via install/setup_deps.sh (option 2).

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

CONTAINER_NAME="oiio-box"
IMAGE="ubuntu:24.04"
ACES_URL="https://github.com/colour-science/OpenColorIO-Configs/releases/download/v1.2/OpenColorIO-Config-ACES-1.2.zip"
ACES_DIR="$HOME/Documents/aces_1.2"

# ── Preflight ────────────────────────────────────────────────────────────────

if ! command -v distrobox &>/dev/null; then
    echo -e "${RED}Error: distrobox is not installed.${NC}"
    echo "  Install with: sudo dnf install distrobox"
    exit 1
fi

echo -e "${GREEN}=== oiio-box Distrobox Setup ===${NC}"
echo ""

# ── 1. Create container ─────────────────────────────────────────────────────

echo -e "${CYAN}[1/4] Creating container ...${NC}"
if distrobox ls 2>/dev/null | grep -q "$CONTAINER_NAME"; then
    echo -e "  ${GREEN}✓${NC} Container '$CONTAINER_NAME' already exists"
else
    distrobox create -n "$CONTAINER_NAME" --image "$IMAGE" -Y
    echo -e "  ${GREEN}✓${NC} Container '$CONTAINER_NAME' created"
fi

# ── 2. Install packages inside container ─────────────────────────────────────

echo -e "${CYAN}[2/4] Installing packages inside container ...${NC}"
distrobox enter "$CONTAINER_NAME" -- bash -c '
    set -e
    sudo apt-get update -qq
    sudo apt-get install -y -qq openimageio-tools opencolorio-tools curl unzip >/dev/null 2>&1
    echo "  Installed: openimageio-tools opencolorio-tools"
    oiiotool --help | head -1
'
echo -e "  ${GREEN}✓${NC} Packages installed"

# ── 3. ACES config ──────────────────────────────────────────────────────────

echo -e "${CYAN}[3/4] ACES 1.2 config ...${NC}"
if [[ -f "$ACES_DIR/config.ocio" ]]; then
    echo -e "  ${GREEN}✓${NC} Already present at $ACES_DIR/config.ocio"
else
    echo -e "  ${YELLOW}→${NC} Downloading ACES 1.2 config ..."
    tmpzip=$(mktemp /tmp/aces_config_XXXXXX.zip)
    if curl -fSL "$ACES_URL" -o "$tmpzip" 2>/dev/null; then
        mkdir -p "$ACES_DIR"
        unzip -qo "$tmpzip" -d "$HOME/Documents/"
        rm -f "$tmpzip"
        if [[ -f "$ACES_DIR/config.ocio" ]]; then
            echo -e "  ${GREEN}✓${NC} ACES 1.2 installed to $ACES_DIR/"
        else
            echo -e "  ${RED}✗${NC} Extraction done but config.ocio not found at expected path"
            echo -e "  ${YELLOW}  Check ~/Documents/ for the extracted folder${NC}"
        fi
    else
        echo -e "  ${RED}✗${NC} Download failed — install ACES config manually"
        rm -f "$tmpzip"
    fi
fi

# ── 4. Wrapper script ───────────────────────────────────────────────────────

echo -e "${CYAN}[4/4] Creating ~/bin/oiiotool wrapper ...${NC}"
mkdir -p "$HOME/bin"

cat > "$HOME/bin/oiiotool" <<'WRAPPER'
#!/bin/bash
# oiiotool wrapper — runs inside the oiio-box distrobox container
# Generated by setup_oiio_container.sh
exec distrobox enter oiio-box -- oiiotool "$@"
WRAPPER
chmod +x "$HOME/bin/oiiotool"
echo -e "  ${GREEN}✓${NC} ~/bin/oiiotool wrapper installed"

# Ensure ~/bin is in PATH and OCIO is set
if ! grep -qF '$HOME/bin' "$HOME/.bashrc" 2>/dev/null; then
    echo '' >> "$HOME/.bashrc"
    echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
    echo -e "  ${GREEN}+${NC} Added ~/bin to PATH in ~/.bashrc"
fi

if ! grep -qF 'export OCIO=' "$HOME/.bashrc" 2>/dev/null; then
    echo "export OCIO=\"$ACES_DIR/config.ocio\"" >> "$HOME/.bashrc"
    echo -e "  ${GREEN}+${NC} Added OCIO env var to ~/.bashrc"
else
    echo -e "  ${GREEN}✓${NC} OCIO already set in ~/.bashrc"
fi

echo ""
echo -e "${GREEN}=== oiio-box ready ===${NC}"
echo ""
echo "Test it:"
echo "  source ~/.bashrc"
echo "  oiiotool --help"
echo "  echo \$OCIO"
echo ""
